import Link from "next/link";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { Header } from "../../components/header";
import { getDb } from "../../lib/prisma";
import { getLocale, t } from "../../lib/i18n";
export const dynamic="force-dynamic";
export default async function AboutPage(){const locale=await getLocale();const x=t[locale];const db=getDb();let profile:any=null,experience:any[]=[],education:any[]=[],certs:any[]=[],achievements:any[]=[];if(db){try{[profile,experience,education,certs,achievements]=await Promise.all([db.profile.findFirst(),db.experience.findMany({where:{visible:true},orderBy:{startDate:'desc'}}),db.education.findMany({where:{visible:true},orderBy:{startDate:'desc'}}),db.certification.findMany({where:{visible:true},orderBy:{issueDate:'desc'}}),db.achievement.findMany({where:{visible:true},orderBy:{date:'desc'}})])}catch{}}
return <main className="min-h-screen"><Header locale={locale}/><div className="mx-auto max-w-6xl px-6 py-16 lg:px-10"><Link href="/" className="button-secondary inline-flex"><ArrowLeft size={16}/>{x.back}</Link><div className="mt-14 max-w-4xl"><p className="text-sm uppercase tracking-[.25em] text-sky-500">About</p><h1 className="mt-3 text-5xl font-semibold tracking-tight">{profile?.title||"The person behind the work."}</h1><p className="mt-6 text-lg leading-8 text-zinc-600 dark:text-zinc-400">{profile?.longBio||profile?.shortBio||"This page is ready for a real biography, background, and learning story. Nothing is invented here."}</p></div>
{experience.length>0&&<section className="mt-20"><h2 className="text-2xl font-semibold">Experience</h2><div className="mt-7 space-y-4">{experience.map(e=><article key={e.id} className="premium-card"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-xl font-semibold">{e.position}</h3><p className="mt-1 text-sky-500">{e.company}</p></div><span className="text-sm text-zinc-500">{e.current?"Present":""}</span></div><p className="mt-4 leading-7 text-zinc-600 dark:text-zinc-400">{e.description}</p></article>)}</div></section>}
{education.length>0&&<section className="mt-20"><h2 className="text-2xl font-semibold">Education</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{education.map(e=><article key={e.id} className="premium-card"><h3 className="text-xl font-semibold">{e.institution}</h3><p className="mt-2 text-sky-500">{[e.degree,e.field].filter(Boolean).join(" · ")}</p><p className="mt-4 leading-7 text-zinc-600 dark:text-zinc-400">{e.description}</p></article>)}</div></section>}
{certs.length>0&&<section className="mt-20"><h2 className="text-2xl font-semibold">Certifications</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{certs.map(c=><article key={c.id} className="premium-card"><h3 className="text-lg font-semibold">{c.name}</h3><p className="mt-1 text-sky-500">{c.issuer}</p>{c.credentialUrl&&<a className="mt-4 inline-flex items-center gap-2 text-sm text-sky-500" href={c.credentialUrl} target="_blank" rel="noreferrer">Credential <ArrowUpRight size={15}/></a>}</article>)}</div></section>}
{achievements.length>0&&<section className="mt-20"><h2 className="text-2xl font-semibold">Achievements</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{achievements.map(a=><article key={a.id} className="premium-card"><h3 className="text-lg font-semibold">{a.title}</h3><p className="mt-3 leading-7 text-zinc-600 dark:text-zinc-400">{a.description}</p></article>)}</div></section>}
</div></main>}
