"use client";
import Link from "next/link";
import { BookOpen, FolderKanban, GraduationCap, LogOut, Settings, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { useRouter } from "next/navigation";

const items = [
  ["Overview", "/admin", Sparkles], ["Blog", "/admin/blog", BookOpen], ["Projects", "/admin/projects", FolderKanban],
  ["Skills", "/admin/skills", ShieldCheck], ["Experience", "/admin/experience", UserRound], ["Education", "/admin/education", GraduationCap],
  ["Certifications", "/admin/certifications", ShieldCheck], ["Profile & Links", "/admin/profile", UserRound], ["Settings", "/admin/settings", Settings],
] as const;
export default function AdminOverview({counts}:{counts:{posts:number;projects:number;skills:number;messages:number}}) {
 return <AdminLayout active="Overview">
   <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Posts",counts.posts,"Blog content"],["Projects",counts.projects,"Real work only"],["Skills",counts.skills,"Honest levels"],["Messages",counts.messages,"Contact inbox"]].map(([t,v,d])=><div key={t as string} className="premium-card"><p className="text-sm text-zinc-500">{t}</p><p className="mt-3 text-3xl font-semibold">{v}</p><p className="mt-2 text-sm text-zinc-500">{d}</p></div>)}</div>
   <div className="mt-6 premium-card"><h2 className="text-xl font-semibold">Your private control center</h2><p className="mt-2 max-w-3xl leading-7 text-zinc-600 dark:text-zinc-400">Everything public on the portfolio can now be managed from here. Keep unfinished material private until you are ready to publish it.</p></div>
 </AdminLayout>;
}
export function AdminLayout({children,active}:{children:React.ReactNode;active:string}){const router=useRouter(); async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/admin/login");router.refresh();} return <main className="min-h-screen"><div className="mx-auto flex max-w-[1500px] gap-6 px-4 py-4 lg:px-6"><aside className="hidden min-h-[calc(100vh-32px)] w-64 shrink-0 flex-col rounded-3xl border border-zinc-200 bg-white/70 p-4 shadow-sm dark:border-white/10 dark:bg-white/[0.025] md:flex"><div className="mb-8 flex items-center gap-3 px-3 pt-2"><div className="grid h-10 w-10 place-items-center rounded-xl bg-sky-500 text-white"><ShieldCheck size={20}/></div><div><p className="font-semibold">Ozaib</p><p className="text-xs text-zinc-500">Admin</p></div></div><nav className="space-y-1">{items.map(([label,href,Icon])=><Link key={href} href={href} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${active===label?"bg-sky-500/10 text-sky-600 dark:text-sky-300":"text-zinc-600 hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-white/5"}`}><Icon size={17}/>{label}</Link>)}</nav><div className="mt-auto border-t border-zinc-200 pt-4 dark:border-white/10"><button onClick={logout} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-zinc-500 hover:bg-zinc-100 dark:hover:bg-white/5"><LogOut size={17}/> Sign out</button></div></aside><div className="mb-3 flex gap-2 overflow-x-auto rounded-2xl border border-zinc-200 bg-white/60 p-2 dark:border-white/10 dark:bg-white/[0.02] md:hidden">{items.map(([label,href])=><Link key={href} href={href} className="whitespace-nowrap rounded-xl px-3 py-2 text-xs hover:bg-zinc-100 dark:hover:bg-white/5">{label}</Link>)}</div><section className="min-w-0 flex-1 rounded-3xl border border-zinc-200 bg-white/60 p-5 shadow-sm dark:border-white/10 dark:bg-white/[0.02] sm:p-7"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-sky-500">Control center</p><h1 className="mt-1 text-3xl font-semibold">{active}</h1></div><div className="flex gap-2"><button className="button-secondary text-sm md:hidden" onClick={()=>router.push('/admin')}>Admin</button><Link href="/" className="button-secondary text-sm">View website</Link></div></div>{children}</section></div></main>;}
