"use client";
import { useState } from "react";
import { Plus, Pencil, Trash2, Save, X } from "lucide-react";

export function AdminForm({children,onSubmit,submitLabel="Save",busy=false}:{children:React.ReactNode;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;submitLabel?:string;busy?:boolean}){return <form onSubmit={onSubmit} className="space-y-5">{children}<div className="flex gap-2"><button disabled={busy} className="button-primary disabled:opacity-50"><Save size={16}/>{busy?"Saving...":submitLabel}</button></div></form>}
export function Field({label,name,defaultValue,type="text",placeholder,multiple=false,required=false}:{label:string;name:string;defaultValue?:string|number;type?:string;placeholder?:string;multiple?:boolean;required?:boolean}){return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{multiple?<textarea name={name} defaultValue={defaultValue as string} placeholder={placeholder} required={required} rows={6} className="admin-input"/>:<input name={name} defaultValue={defaultValue} type={type} placeholder={placeholder} required={required} className="admin-input"/>}</label>}
export function Select({label,name,defaultValue,options}:{label:string;name:string;defaultValue?:string;options:[string,string][]}){return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span><select name={name} defaultValue={defaultValue} className="admin-input">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
export function Check({label,name,defaultChecked}:{label:string;name:string;defaultChecked?:boolean}){return <label className="flex items-center gap-3 text-sm"><input name={name} type="checkbox" defaultChecked={defaultChecked} className="h-4 w-4"/>{label}</label>}
export function ManagerShell({title,description,items,empty,children,onDelete}:{title:string;description:string;items:any[];empty:string;children:(item:any,onDone:()=>void)=>React.ReactNode;onDelete:(id:string)=>void}){const [editing,setEditing]=useState<any>(null); const [adding,setAdding]=useState(false); return <div><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-zinc-500">{description}</p></div><button className="button-primary" onClick={()=>{setEditing(null);setAdding(true)}}><Plus size={17}/> Add new</button></div>{(adding||editing)?<div className="mb-6 premium-card"><div className="mb-5 flex items-center justify-between"><h3 className="font-semibold">{editing?"Edit item":"New item"}</h3><button onClick={()=>{setAdding(false);setEditing(null)}} className="icon-link"><X size={16}/></button></div>{children(editing,()=>{setAdding(false);setEditing(null)})}</div>:null}<div className="space-y-3">{items.length===0?<div className="premium-card text-sm text-zinc-500">{empty}</div>:items.map(item=><div key={item.id} className="flex flex-col gap-4 rounded-2xl border border-zinc-200 bg-white/50 p-4 dark:border-white/10 dark:bg-white/[0.02] sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="font-medium">{item.title||item.name}</p><p className="mt-1 truncate text-sm text-zinc-500">{item.shortDesc||item.excerpt||item.category||item.level||""}</p></div><div className="flex gap-2"><button className="button-secondary text-sm" onClick={()=>{setEditing(item);setAdding(false)}}><Pencil size={15}/> Edit</button><button className="button-secondary text-sm text-red-500" onClick={()=>onDelete(item.id)}><Trash2 size={15}/> Delete</button></div></div>)}</div></div>}
