import { NextResponse } from "next/server";
import { requireAdmin } from "../../../../../lib/auth";
import { getDb } from "../../../../../lib/prisma";
const allowed=["post","project","skill","experience","education","certification","socialLink","siteSettings","profile"] as const;
function ok(r:string){return (allowed as readonly string[]).includes(r)}
function clean(v:any){if(v===undefined||v===null)return v;if(typeof v!=="string")return v;const s=v.trim();return s===""?null:s}
function payload(resource:string,b:any){const base:any={...b};["id","createdAt","updatedAt"].forEach(k=>delete base[k]);for(const k of Object.keys(base))if(typeof base[k]==="string")base[k]=clean(base[k]);if(resource==="post"){base.featured=!!b.featured;base.publishedAt=b.publishedAt?new Date(b.publishedAt):b.status==="PUBLISHED"?new Date():null;base.scheduledAt=b.scheduledAt?new Date(b.scheduledAt):null}if(resource==="project") {base.featured=!!b.featured;base.visible=b.visible!==false}if(["skill","experience","education","certification","socialLink"].includes(resource))base.visible=b.visible!==false;if(resource==="skill"||resource==="socialLink")base.sortOrder=Number(b.sortOrder||0);return base}
export async function PATCH(req:Request,{params}:{params:Promise<{resource:string;id:string}>}){const s=await requireAdmin();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const {resource,id}=await params;if(!ok(resource))return NextResponse.json({error:"Not found"},{status:404});const db=getDb();if(!db)return NextResponse.json({error:"DATABASE_URL is not configured"},{status:503});try{const data=await (db as any)[resource].update({where:{id},data:payload(resource,await req.json())});return NextResponse.json(data)}catch(e){return NextResponse.json({error:"Could not update item."},{status:400})}}
export async function DELETE(_req:Request,{params}:{params:Promise<{resource:string;id:string}>}){const s=await requireAdmin();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const {resource,id}=await params;if(!ok(resource))return NextResponse.json({error:"Not found"},{status:404});const db=getDb();if(!db)return NextResponse.json({error:"DATABASE_URL is not configured"},{status:503});try{await (db as any)[resource].delete({where:{id}});return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:"Could not delete item."},{status:400})}}
